In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv('GEFCom2014-E - Copy.csv').dropna()
df1=df.drop('load',axis=1)

In [3]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
names = df1.columns
d = scaler.fit_transform(df1)
data = pd.DataFrame(d, columns=names)

In [4]:
df2=pd.read_csv('GEFCom2014-E.csv').dropna()
df2.iloc[:61368]

             Date  Hour    load      T
17544  01-01-2006     1  3010.0  22.67
17545  01-01-2006     2  2853.0  20.67
17546  01-01-2006     3  2758.0  21.33
17547  01-01-2006     4  2705.0  19.00
17548  01-01-2006     5  2709.0  19.33
...           ...   ...     ...    ...
78907  31-12-2012    20  3769.0  28.67
78908  31-12-2012    21  3585.0  28.67
78909  31-12-2012    22  3407.0  28.33
78910  31-12-2012    23  3219.0  29.00
78911  31-12-2012    24  3035.0  29.00

[61368 rows x 4 columns]

In [5]:
X_train=data.iloc[17544:61368]
y_train=df['load'].iloc[17544:61368]/1000
X_test=data.iloc[61368:]
y_test=df['load'].iloc[61368:]/1000

In [6]:
# LR

X_train=data.iloc[17544:61368]
y_train=df['load'].iloc[17544:61368]/1000
X_test=data.iloc[61368:]
y_test=df['load'].iloc[61368:]/1000
X_train=X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
y_train=y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)


from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

ypred=regressor.predict(X_test)
print('Results for Linear Regression')
# Import accuracy score 
from sklearn.metrics import accuracy_score

#For MAE
mae=np.mean(np.abs(ypred-y_test))
print('MAE = {:.2f} (%)'.format(mae))

#For MAPE
def mean_absolute_percentage_error(y_test, ypred): 
    return np.mean(np.abs((y_test - ypred)/y_test))*100.
mape = mean_absolute_percentage_error(y_test, ypred)
print('MAPE = {:.2f} (%)'.format(mape))

# For RMSE
from sklearn.metrics import mean_squared_error 
mse=mean_squared_error(y_test,ypred) 
rsme=np.sqrt(mse) 
print('RSME = {:.2f} (%)'.format(rsme))
ylr=ypred

Results for Linear Regression
MAE = 0.40 (%)
MAPE = 12.06 (%)
RSME = 0.50 (%)